// GENERATED: Do not edit by hand. Source: firebase_list_with_tickets.csv
import { getLocationText } from "../utils/constants";

export type Attendee = {
  email: string;
  fullName: string;
  ticketNumber: string;
  ticketType?: string;
  location: string;
};

export type BaseAttendee = Omit<Attendee, "location">;

export const BASE_ATTENDEES: BaseAttendee[] = [
  { email: `adetunjilabi@gmail.com`, fullName: `Babatunde`, ticketNumber: `CONF-ATIN19748`, ticketType: `Conference Access` },
  { email: `contact@promoboxng.com`, fullName: `Mitchell`, ticketNumber: `CONF-ATIN25180`, ticketType: `Conference Access` },
  { email: `classicusrentals@gmail.com`, fullName: `Akinboye`, ticketNumber: `CONF-ATIN2525`, ticketType: `Conference Access` },
  { email: `seun.kukoyi@gmail.com`, fullName: `Kukoyi`, ticketNumber: `CONF-ATIN25943`, ticketType: `Conference Access` },
  { email: `kunle.ksquare@gmail.com`, fullName: `Kunle`, ticketNumber: `CONF-ATIN28618`, ticketType: `Conference Access` },
  { email: `olamide.rjr@gmail.com`, fullName: `Olamide`, ticketNumber: `CONF-ATIN2965`, ticketType: `Conference Access` },
  { email: `kuwajoseyi@gmail.com`, fullName: `Onome`, ticketNumber: `CONF-ATIN30446`, ticketType: `Conference Access` },
  { email: `tolu.aderogba@rapidrentalsng.com`, fullName: `Tolu`, ticketNumber: `CONF-ATIN34798`, ticketType: `Conference Access` },
  { email: `psalmwyse@gmail.com`, fullName: `Samuel`, ticketNumber: `CONF-ATIN39277`, ticketType: `Conference Access` },
  { email: `grandestevent@gmail.com`, fullName: `Bose`, ticketNumber: `CONF-ATIN42435`, ticketType: `Conference Access` },
  { email: `aplusdrinks@gmail.com`, fullName: `Chibuzo`, ticketNumber: `CONF-ATIN42918`, ticketType: `Conference Access` },
  { email: `ogunlesidamir@yahoo.com`, fullName: `Emmanuel`, ticketNumber: `CONF-ATIN4532`, ticketType: `Conference Access` },
  { email: `lararawa@yahoo.co.uk`, fullName: `Lara`, ticketNumber: `CONF-ATIN55092`, ticketType: `Conference Access` },
  { email: `fadekemi@promoboxng.com`, fullName: `Fadekemi`, ticketNumber: `CONF-ATIN56290`, ticketType: `Conference Access` },
  { email: `drubeeconsulting@gmail.com`, fullName: `Deborah`, ticketNumber: `CONF-ATIN60155`, ticketType: `Conference Access` },
  { email: `ajokealamala1@gmail.com`, fullName: `Ajoke`, ticketNumber: `CONF-ATIN60912`, ticketType: `Conference Access` },
  { email: `moontopevents@gmail.com`, fullName: `Seun`, ticketNumber: `CONF-ATIN72466`, ticketType: `Conference Access` },
  { email: `agelessagency@gmail.com`, fullName: `GRACE`, ticketNumber: `CONF-ATIN73592`, ticketType: `Conference Access` },
  { email: `daniel@eventfulnigeria.com`, fullName: `Daniel`, ticketNumber: `CONF-ATIN746`, ticketType: `Conference Access` },
  { email: `splendoursartrepublic@gmail.com`, fullName: `Splendour`, ticketNumber: `CONF-ATIN80287`, ticketType: `Conference Access` },
  { email: `toyosicsi@gmail.com`, fullName: `Toyosi`, ticketNumber: `CONF-ATIN84484`, ticketType: `Conference Access` },
  { email: `eventsstyledbyberry@gmail.com`, fullName: `Bukola`, ticketNumber: `CONF-ATIN85308`, ticketType: `Conference Access` },
  { email: `atteventcommunication@yahoo.com`, fullName: `Adeyemi`, ticketNumber: `CONF-ATIN988`, ticketType: `Conference Access` },
  { email: `mutchabraham18@gmail.com`, fullName: `Mutch`, ticketNumber: `DINE-ATIN65390`, ticketType: `Dinner Gala Only` },
  { email: `patog2303@gmail.com`, fullName: `Adefunke`, ticketNumber: `EXEC-ATIN11931`, ticketType: `Executive Access` },
  { email: `chinwe.attoh@eventsbybncfabs.com`, fullName: `Chinwe`, ticketNumber: `EXEC-ATIN13400`, ticketType: `Executive Access` },
  { email: `inkland.official@gmail.com`, fullName: `OLAYINKA`, ticketNumber: `EXEC-ATIN15677`, ticketType: `Executive Access` },
  { email: `judith@atinuda.africa`, fullName: `Judith`, ticketNumber: `EXEC-ATIN22725`, ticketType: `Executive Access` },
  { email: `oshojoyce01@gmail.com`, fullName: `Joyce`, ticketNumber: `EXEC-ATIN23095`, ticketType: `Executive Access` },
  { email: `ngovivee@yahoo.com`, fullName: `Ngozi`, ticketNumber: `EXEC-ATIN23264`, ticketType: `Executive Access` },
  { email: `yazyakubu@gmail.com`, fullName: `Yakubu`, ticketNumber: `EXEC-ATIN28779`, ticketType: `Executive Access` },
  { email: `adebola@emeraldandgold.com`, fullName: `Adebola`, ticketNumber: `EXEC-ATIN34509`, ticketType: `Executive Access` },
  { email: `taofikganiyu@gmail.com`, fullName: `Ganiyu`, ticketNumber: `EXEC-ATIN35588`, ticketType: `Executive Access` },
  { email: `jmceventz@gmail.com`, fullName: `Endurance`, ticketNumber: `EXEC-ATIN36333`, ticketType: `Executive Access` },
  { email: `abinibicottage@gmail.com`, fullName: `OLAWUYI`, ticketNumber: `EXEC-ATIN41935`, ticketType: `Executive Access` },
  { email: `marysatella@yahoo.com`, fullName: `Folashade`, ticketNumber: `EXEC-ATIN46982`, ticketType: `Executive Access` },
  { email: `comfortworldcakes@gmail.com`, fullName: `Comfort`, ticketNumber: `EXEC-ATIN59550`, ticketType: `Executive Access` },
  { email: `ebe.marian@gmail.com`, fullName: `Marian`, ticketNumber: `EXEC-ATIN606`, ticketType: `Executive Access` },
  { email: `petersyemi@yahoo.com`, fullName: `Yemisi`, ticketNumber: `EXEC-ATIN61988`, ticketType: `Executive Access` },
  { email: `admin.manager@eventdesign.studio`, fullName: `Juyin`, ticketNumber: `EXEC-ATIN63678`, ticketType: `Executive Access` },
  { email: `iamtheamazingwoman@gmail.com`, fullName: `Buchi`, ticketNumber: `EXEC-ATIN66337`, ticketType: `Executive Access` },
  { email: `bluberry.cakes@gmail.com`, fullName: `Itohan`, ticketNumber: `EXEC-ATIN69550`, ticketType: `Executive Access` },
  { email: `arin@atinuda.africa`, fullName: `Arinola`, ticketNumber: `EXEC-ATIN70408`, ticketType: `Executive Access` },
  { email: `delonixmgtservices@gmail.com`, fullName: `Olajumoke`, ticketNumber: `EXEC-ATIN71146`, ticketType: `Executive Access` },
  { email: `dwseventsng@gmail.com`, fullName: `Adesuwa`, ticketNumber: `EXEC-ATIN72006`, ticketType: `Executive Access` },
  { email: `theeventgirlng@gmail.com`, fullName: `Vivienne`, ticketNumber: `EXEC-ATIN75114`, ticketType: `Executive Access` },
  { email: `beentychops@gmail.com`, fullName: `Binta`, ticketNumber: `PREM-ATIN17946`, ticketType: `Premium Experience` },
  { email: `adebola@emeraldandgold.com`, fullName: `Adebola`, ticketNumber: `PREM-ATIN29610`, ticketType: `Premium Experience` },
  { email: `ugo@atinuda.africa`, fullName: `Ugo`, ticketNumber: `PREM-ATIN32749`, ticketType: `Premium Experience` },
  { email: `lemonytouch@gmail.com`, fullName: `Adeola`, ticketNumber: `PREM-ATIN35851`, ticketType: `Premium Experience` },
  { email: `billings@eventdesign.studio`, fullName: `Segun`, ticketNumber: `PREM-ATIN3882`, ticketType: `Premium Experience` },
  { email: `nosa@delyorkgroup.com`, fullName: `Nosa`, ticketNumber: `PREM-ATIN52924`, ticketType: `Premium Experience` },
  { email: `hello@atmospheric.com.ng`, fullName: `Nike`, ticketNumber: `PREM-ATIN58103`, ticketType: `Premium Experience` },
  { email: `gbemiope@hotmail.com`, fullName: `Gbemisola`, ticketNumber: `PREM-ATIN60077`, ticketType: `Premium Experience` },
  { email: `billings@eventdesign.studio`, fullName: `Segun`, ticketNumber: `PREM-ATIN63187`, ticketType: `Premium Experience` },
  { email: `partnership@myeventigo.com`, fullName: `Oluwadara`, ticketNumber: `PREM-ATIN73973`, ticketType: `Premium Experience` },
  { email: `tpcnig@gmail.com`, fullName: `The Planning`, ticketNumber: `PREM-ATIN74718`, ticketType: `Premium Experience` },
  { email: `stylista.ng@gmail.com`, fullName: `Olubunmi`, ticketNumber: `PREM-ATIN79024`, ticketType: `Executive Access` },
  { email: `justweddingsinspired@yahoo.com`, fullName: `Akintayo`, ticketNumber: `PREM-ATIN80238`, ticketType: `Premium Experience` },
  { email: `damilare@atinuda.africa`, fullName: `Damilare`, ticketNumber: `PREM-ATIN81311`, ticketType: `Premium Experience` },
  { email: `letoyaxo@icloud.com`, fullName: `Toya`, ticketNumber: `PREM-ATIN83303`, ticketType: `Premium Experience` },
  { email: `devicemanagers72@gmail.com`, fullName: `IKECHUKWU`, ticketNumber: `PREM-ATIN83511`, ticketType: `Premium Experience` },
  { email: `aksentevent@gmail.com`, fullName: `Augustine`, ticketNumber: `PREM-ATIN87531`, ticketType: `Premium Experience` },
  { email: `billings@eventdesign.studio`, fullName: `Segun`, ticketNumber: `PREM-ATIN9651`, ticketType: `Premium Experience` },
  { email: `classeventz@gmail.com`, fullName: `Uche`, ticketNumber: `SIG-ATIN43047`, ticketType: `Signature Pass` },
  { email: `u.rennaiye@gmail.com`, fullName: `Laait`, ticketNumber: `WRK-ATIN16916`, ticketType: `Workshop Access` },
  { email: `abigail.niemogha@eventsbybncfabs.com`, fullName: `Abigail`, ticketNumber: `WRK-ATIN21928`, ticketType: `Workshop Access` },
  { email: `oyinlola.davies@eventsbybncfabs.com`, fullName: `Oyinlola`, ticketNumber: `WRK-ATIN33759`, ticketType: `Workshop Access` },
  { email: `sammiejaybar@gmail.com`, fullName: `Samson`, ticketNumber: `WRK-ATIN47810`, ticketType: `Workshop Access` },
  { email: `yinkaosaji@gmail.com`, fullName: `Olayinka`, ticketNumber: `WRK-ATIN54323`, ticketType: `Workshop Access` },
  { email: `tbc`, fullName: `Lagos State Government`, ticketNumber: `EXEC-ATIN23374`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `Oaken Events`, ticketNumber: `EXEC-ATIN94851`, ticketType: `Executive Access` },
  { email: `hana.oda@thelagoscontinental.com`, fullName: `Lagos Continental`, ticketNumber: `EXEC-ATIN49808`, ticketType: `Executive Access` },
  { email: `j.ozokwelu@nordmotion.com`, fullName: `Nord Motors`, ticketNumber: `EXEC-ATIN32008`, ticketType: `Executive Access` },
  { email: `tino4k@gmail.com
akwasi@maxbalo.com`, fullName: `GIAC Group & Maxbalo`, ticketNumber: `EXEC-ATIN98061`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `The Wedding Guru`, ticketNumber: `EXEC-ATIN56855`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `Fara and Zara`, ticketNumber: `EXEC-ATIN29174`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `Yvent Kouture`, ticketNumber: `EXEC-ATIN92165`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `Stage Makers`, ticketNumber: `EXEC-ATIN89082`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `Vento Furniture`, ticketNumber: `EXEC-ATIN61470`, ticketType: `Executive Access` },
  { email: `beautifulideasng@gmail.com`, fullName: `Beautiful Ideas Design`, ticketNumber: `EXEC-ATIN84672`, ticketType: `Executive Access` },
  { email: `ogheneyoma.isioye@orikigroup.com`, fullName: `Oriki Spa`, ticketNumber: `EXEC-ATIN99938`, ticketType: `Executive Access` },
  { email: `tbc`, fullName: `Diageo`, ticketNumber: `EXEC-ATIN65870`, ticketType: `Executive Access` },
  { email: `deolapaulinyang@gmail.com`, fullName: `Abella Olfactory`, ticketNumber: `EXEC-ATIN52913`, ticketType: `Executive Access` },
  { email: `silver sponsor`, fullName: `Dribrix Rentals`, ticketNumber: `EXEC-ATIN20914`, ticketType: `Executive Access` },
  { email: `silver sponsor`, fullName: `Miele Nigeria Experience Centre`, ticketNumber: `EXEC-ATIN68178`, ticketType: `Executive Access` },
  { email: `omoladea@yahoo.com`, fullName: `Astoria Caterers`, ticketNumber: `EXEC-ATIN42034`, ticketType: `Executive Access` },
  { email: `pcfngltd@gmail.com`, fullName: `The paper packaging company`, ticketNumber: `CONF-ATIN43181`, ticketType: `Conference Access` },
  { email: `serendipityadeniji@yahoo.com`, fullName: `OrchidButter Studio`, ticketNumber: `CONF-ATIN46649`, ticketType: `Conference Access` },
  { email: `stefireo@gmail.com`, fullName: `Concepteur-De-Fruitee Limited (CDF-Desserts)`, ticketNumber: `CONF-ATIN96877`, ticketType: `Conference Access` },
  { email: `redwooddoublesolutions@gmail.com`, fullName: `Redwood Double Solutions`, ticketNumber: `CONF-ATIN61060`, ticketType: `Conference Access` },
  { email: `larfida98@gmail.com`, fullName: `larfida signature`, ticketNumber: `CONF-ATIN43062`, ticketType: `Conference Access` },
  { email: `tokeas@ymail.com`, fullName: `Bekiri`, ticketNumber: `CONF-ATIN48370`, ticketType: `Conference Access` },
  { email: `mofeagbajor@gmail.com`, fullName: `Scubed Juice`, ticketNumber: `CONF-ATIN35550`, ticketType: `Conference Access` },
  { email: `abiclement234@gmail.com`, fullName: `Fruitieworld`, ticketNumber: `CONF-ATIN83937`, ticketType: `Conference Access` },
  { email: `medicalambulanceservices@gmail.com`, fullName: `Medical Ambulance Service`, ticketNumber: `CONF-ATIN20657`, ticketType: `Conference Access` },
  { email: `medicalambulanceservices@gmail.com`, fullName: `Medical Ambulance Service`, ticketNumber: `CONF-ATIN39445`, ticketType: `Conference Access` },
  { email: `seun.kukoyi@gmail.com`, fullName: `Joks pepper Konsult`, ticketNumber: `CONF-ATIN35538`, ticketType: `Conference Access` },
  { email: `doubles.martins@gmail.com`, fullName: `Zivang`, ticketNumber: `CONF-ATIN65862`, ticketType: `Conference Access` },
  { email: `kfarentals@gmail.com`, fullName: `KFA`, ticketNumber: `CONF-ATIN48969`, ticketType: `Conference Access` },
  { email: `clesteem2010@gmail.com`, fullName: `Post My Event`, ticketNumber: `CONF-ATIN13826`, ticketType: `Conference Access` },
  { email: `ayizayaodufuwa@gmail.com`, fullName: `Aplus Drinks Limited`, ticketNumber: `CONF-ATIN63992`, ticketType: `Conference Access` },
  { email: `nosa@delyorkgroup.com`, fullName: `Del-York Group`, ticketNumber: `CONF-ATIN20931`, ticketType: `Conference Access` },
  { email: `spicylarry2@gmail.com`, fullName: `Larryspice smallchops`, ticketNumber: `CONF-ATIN51191`, ticketType: `Conference Access` },
  { email: `kontractklear@gmail.com`, fullName: `Kontract Klear Enterprises`, ticketNumber: `CONF-ATIN80076`, ticketType: `Conference Access` },
  { email: `tashbistro@office.com`, fullName: `Tash Bistro`, ticketNumber: `CONF-ATIN47213`, ticketType: `Conference Access` },
  { email: `molproductions22@gmail.com`, fullName: `Mol Productions`, ticketNumber: `CONF-ATIN89528`, ticketType: `Conference Access` },
  { email: `feyiakisanya@gmail.com`, fullName: `Ajoke Alamala`, ticketNumber: `CONF-ATIN40648`, ticketType: `Conference Access` },
  { email: `happyhour@limehousebars.com`, fullName: `Limehouse Bars`, ticketNumber: `CONF-ATIN26231`, ticketType: `Conference Access` },
  { email: `info@saheetosmallchops.com`, fullName: `Saheeto Small Chops`, ticketNumber: `CONF-ATIN43748`, ticketType: `Conference Access` },
  { email: `info@virginhospitality.com`, fullName: `Virgin Hospitality Company/ Virgin Vie Angel Limited`, ticketNumber: `CONF-ATIN11155`, ticketType: `Conference Access` },
  { email: `grindconcepts@gmail.com`, fullName: `Grind & Grill`, ticketNumber: `CONF-ATIN81364`, ticketType: `Conference Access` },
  { email: `lolades@gmail.com`, fullName: `Authentic Cuisine`, ticketNumber: `CONF-ATIN23272`, ticketType: `Conference Access` },
  { email: `yagazie@gazmadustudios.com`, fullName: `Gazmadu  Studios`, ticketNumber: `CONF-ATIN86091`, ticketType: `Conference Access` },
  { email: `olukunle.folarin@tvccommunications.tv`, fullName: `TVC`, ticketNumber: `CONF-ATIN79532`, ticketType: `Conference Access` },
  { email: `nikeadeniyi@gmail.com`, fullName: `Djaime Faith`, ticketNumber: `CONF-ATIN50716`, ticketType: `Conference Access` },
  { email: `ahovebusola@gmail.com`, fullName: `Bolarinwa & Co`, ticketNumber: `CONF-ATIN46234`, ticketType: `Conference Access` },
  { email: `tbc`, fullName: `Jubilee Infinitee`, ticketNumber: `CONF-ATIN37006`, ticketType: `Conference Access` },
  { email: `thedessertstudio@yahoo.com`, fullName: `The Dessert Studios`, ticketNumber: `CONF-ATIN52487`, ticketType: `Conference Access` },
  { email: `nan`, fullName: `Bukola`, ticketNumber: `EXEC-ATIN71168`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Akpo-olade Okoro`, ticketNumber: `EXEC-ATIN84906`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Christine OluShola Adeyanju`, ticketNumber: `EXEC-ATIN61090`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Nkem Sofela`, ticketNumber: `EXEC-ATIN73369`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Uzo Orimalade`, ticketNumber: `EXEC-ATIN71376`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Emilomo Oputteh`, ticketNumber: `EXEC-ATIN54702`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Kofo Abayomi`, ticketNumber: `EXEC-ATIN38649`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ejiofor Onyinyechi`, ticketNumber: `EXEC-ATIN43836`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ini Abimbola`, ticketNumber: `EXEC-ATIN80306`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Emmanuel Evans`, ticketNumber: `EXEC-ATIN52906`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Tokunbo BaborEgeregor`, ticketNumber: `EXEC-ATIN56485`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Tara Aisida`, ticketNumber: `EXEC-ATIN10768`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Temitope Oladapo`, ticketNumber: `EXEC-ATIN79844`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Oluwole Mayungbo`, ticketNumber: `EXEC-ATIN18592`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Otsaye Wagbatsoma`, ticketNumber: `EXEC-ATIN19547`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ithior Sedi pius`, ticketNumber: `EXEC-ATIN19311`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Olamidayo Akinsete`, ticketNumber: `EXEC-ATIN95645`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Anuri Iyalla`, ticketNumber: `EXEC-ATIN42393`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Lemuel Iyalla`, ticketNumber: `EXEC-ATIN43260`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Eme Aderinokun`, ticketNumber: `EXEC-ATIN21242`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Dr omotayo adeniji`, ticketNumber: `EXEC-ATIN76909`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Bisi Sotunde`, ticketNumber: `EXEC-ATIN13507`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Nene Obichie`, ticketNumber: `EXEC-ATIN84782`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ovwe Sowho`, ticketNumber: `EXEC-ATIN34173`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Motolani Ladipo`, ticketNumber: `EXEC-ATIN87755`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Oluwafunbi Akinyosoye`, ticketNumber: `EXEC-ATIN38658`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Akintola Joshua Mayowa`, ticketNumber: `EXEC-ATIN22342`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Tunde Alade`, ticketNumber: `EXEC-ATIN41741`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Raliat Ibrahim Oyetunde`, ticketNumber: `EXEC-ATIN20249`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Blessing Patrice-AL'OM`, ticketNumber: `EXEC-ATIN28262`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ezinne Okuku`, ticketNumber: `EXEC-ATIN95230`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Femi Oladunmoye`, ticketNumber: `EXEC-ATIN22464`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Uzoma Dania`, ticketNumber: `EXEC-ATIN91491`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ada Aire`, ticketNumber: `EXEC-ATIN75001`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Bawo Ikomi`, ticketNumber: `EXEC-ATIN65601`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Aboyowa Ikomi`, ticketNumber: `EXEC-ATIN11040`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Temitayo Omisore`, ticketNumber: `EXEC-ATIN59008`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Kate Owoyele`, ticketNumber: `EXEC-ATIN32582`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Blessing Ikharia`, ticketNumber: `EXEC-ATIN16414`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Funmilayo`, ticketNumber: `EXEC-ATIN95324`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Charles Odii`, ticketNumber: `EXEC-ATIN55088`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Seyi Olusanya`, ticketNumber: `EXEC-ATIN79809`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Yewande Zacchaeus`, ticketNumber: `EXEC-ATIN63176`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Temilola Adepetun`, ticketNumber: `EXEC-ATIN20029`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Toke Benson`, ticketNumber: `EXEC-ATIN67867`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Lilian Olubi`, ticketNumber: `EXEC-ATIN39788`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Leo Stan Ekeh`, ticketNumber: `EXEC-ATIN88899`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Mary Akpobome`, ticketNumber: `EXEC-ATIN29286`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Angela Jide-Jones`, ticketNumber: `EXEC-ATIN58680`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Obafemi Banigbe`, ticketNumber: `EXEC-ATIN23359`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Chioma Adure Nwog-Johnson`, ticketNumber: `EXEC-ATIN58604`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Jennifer Odufuwa`, ticketNumber: `EXEC-ATIN77143`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Christine Ogbeh`, ticketNumber: `EXEC-ATIN74301`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Bryan Tachie-Menson`, ticketNumber: `EXEC-ATIN99106`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Abokuma Ellis`, ticketNumber: `EXEC-ATIN94719`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Debola Lewis`, ticketNumber: `EXEC-ATIN78233`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Eunice Showunmi-Adeyemi`, ticketNumber: `EXEC-ATIN47649`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Gbemisola Ope`, ticketNumber: `EXEC-ATIN23719`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Samke Mhlonge`, ticketNumber: `EXEC-ATIN36480`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ajibade Laolu-Adewale`, ticketNumber: `EXEC-ATIN55447`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Oluwatosin Olaseinde`, ticketNumber: `EXEC-ATIN92288`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Omeiza Alao`, ticketNumber: `EXEC-ATIN28540`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Titi Oshodi`, ticketNumber: `EXEC-ATIN26186`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Dr. Martin Kwende, MBA, PHD`, ticketNumber: `EXEC-ATIN43986`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Sophie Masipa`, ticketNumber: `EXEC-ATIN81314`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `nan`, ticketNumber: `EXEC-ATIN24306`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Isabella Adediji`, ticketNumber: `EXEC-ATIN46246`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Judy Udeze`, ticketNumber: `EXEC-ATIN66088`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Olivia Okeke`, ticketNumber: `EXEC-ATIN10600`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Stephanie Olopade`, ticketNumber: `EXEC-ATIN72272`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Akwasi Peprah`, ticketNumber: `EXEC-ATIN98744`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Mary Ojulari`, ticketNumber: `EXEC-ATIN88970`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Juliet Ibrahim`, ticketNumber: `EXEC-ATIN39271`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Salem King`, ticketNumber: `EXEC-ATIN24641`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Tokunboh George- Taylor`, ticketNumber: `EXEC-ATIN20799`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Claudia Lumor`, ticketNumber: `EXEC-ATIN48530`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Chichi Nwoko`, ticketNumber: `EXEC-ATIN37210`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Bisola Borha Arigbe`, ticketNumber: `EXEC-ATIN17157`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ezinne Chinkata`, ticketNumber: `EXEC-ATIN88566`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Frank Osodi Richard`, ticketNumber: `EXEC-ATIN26094`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Clare Omatseye`, ticketNumber: `EXEC-ATIN46269`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Oladipupo Akinkunmi Joseph`, ticketNumber: `EXEC-ATIN10917`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Damon Haley`, ticketNumber: `EXEC-ATIN75516`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Kelvin Okafor`, ticketNumber: `EXEC-ATIN45874`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ayo Mario-Ese`, ticketNumber: `EXEC-ATIN26821`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Stephanie Busari`, ticketNumber: `EXEC-ATIN97506`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Queen Murielle`, ticketNumber: `EXEC-ATIN54323`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Tokunboh George-Taylor`, ticketNumber: `EXEC-ATIN12372`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Fisayo Beecroft`, ticketNumber: `EXEC-ATIN30784`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Uzo Orimalade`, ticketNumber: `EXEC-ATIN38128`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Ifunanya Igwe`, ticketNumber: `EXEC-ATIN48081`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Kamil Olufowobi`, ticketNumber: `EXEC-ATIN29911`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Oscar Oyinsan`, ticketNumber: `EXEC-ATIN31239`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Alexander Amosu`, ticketNumber: `EXEC-ATIN18283`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Gbemi Shasore`, ticketNumber: `EXEC-ATIN31858`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `George Okoro`, ticketNumber: `EXEC-ATIN34040`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Henry	 Nwaeze`, ticketNumber: `EXEC-ATIN91554`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Diann Valentine`, ticketNumber: `EXEC-ATIN91030`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Lincoln Alexander`, ticketNumber: `EXEC-ATIN86960`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Stella Fubara`, ticketNumber: `EXEC-ATIN52201`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `TY Bello`, ticketNumber: `EXEC-ATIN84893`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Justin Irabor`, ticketNumber: `EXEC-ATIN33088`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Abasiama Idaresit`, ticketNumber: `EXEC-ATIN76154`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `IB Quake`, ticketNumber: `EXEC-ATIN68595`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Adaora Lumina`, ticketNumber: `EXEC-ATIN17995`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Riyah Abdul Karim`, ticketNumber: `EXEC-ATIN40159`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Oscar Ukonu`, ticketNumber: `EXEC-ATIN79673`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Dr. Pink`, ticketNumber: `EXEC-ATIN18267`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Cynthia Ejimnkeonye`, ticketNumber: `EXEC-ATIN30136`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Hon. Sam Egube`, ticketNumber: `EXEC-ATIN15439`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Kelechi Amadi`, ticketNumber: `EXEC-ATIN96740`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Stephaine Olopade`, ticketNumber: `EXEC-ATIN73237`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Temi Badru (MC)`, ticketNumber: `EXEC-ATIN35955`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Tolulope Oladipupo`, ticketNumber: `EXEC-ATIN81374`, ticketType: `Executive Access` },
  { email: `nan`, fullName: `Veronica Ebie`, ticketNumber: `EXEC-ATIN65000`, ticketType: `Executive Access` }
];

export const ATTENDEES: Attendee[] = BASE_ATTENDEES.map(a => ({
  ...a,
  location: getLocationText(a.ticketType || ""),
}));

export default ATTENDEES;
